name: Delete Merged Branch

on:
  pull_request:
    types:
      - closed

jobs:
  delete_branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }} # Checkout the target branch

      - name: Delete source branch
        run: |
          git push origin --delete ${{ github.event.pull_request.head.ref }}
